<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <ProjectReference Include="..\StudentsAffairs.Web.Client\StudentsAffairs.Web.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StudentsAffairs.Infrastructure\StudentsAffairs.Infrastructure.csproj" />
    <ProjectReference Include="..\StudentsAffairs.Application\StudentsAffairs.Application.csproj" />
    <ProjectReference Include="..\StudentsAffairs.Shared\StudentsAffairs.Shared.csproj" />
  </ItemGroup>

</Project>
